"""empty message

Revision ID: 1af75bd094fc
Revises: 7f83a0247dd8
Create Date: 2020-05-02 15:26:02.426456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af75bd094fc'
down_revision = '7f83a0247dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('un_id', sa.Integer(), nullable=False))
    op.alter_column('students', 'notes',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.create_unique_constraint(None, 'students', ['un_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'notes',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('students', 'un_id')
    # ### end Alembic commands ###
