"""empty message

Revision ID: 605aed713ce7
Revises: 6c0c6736427d
Create Date: 2020-04-30 13:30:08.022498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605aed713ce7'
down_revision = '6c0c6736427d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'email')
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
