"""empty message

Revision ID: 68e2d59f1a33
Revises: e7c0ea5b08a5
Create Date: 2020-05-02 16:09:03.302706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e2d59f1a33'
down_revision = 'e7c0ea5b08a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('barcode_path', sa.String(length=80), nullable=True))
    op.add_column('students', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'image')
    op.drop_column('students', 'barcode_path')
    # ### end Alembic commands ###
