"""empty message

Revision ID: e7c0ea5b08a5
Revises: 1af75bd094fc
Create Date: 2020-05-02 15:36:07.141283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c0ea5b08a5'
down_revision = '1af75bd094fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('level_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('major_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'major', ['major_id'], ['id'])
    op.create_foreign_key(None, 'students', 'level', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'major_id')
    op.drop_column('students', 'level_id')
    # ### end Alembic commands ###
